name: android_build

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3 # 更新为 v3 版本

      - name: Set up JDK
        uses: actions/setup-java@v3 # 更新为 v3 版本
        with:
          java-version: '17' # 推荐使用较新版本的 Java，如 17 或者根据项目需求选择

      - name: Build the app
        run: |
          chmod +x gradlew # 给予执行权限
          ./gradlew assembleDebug --stacktrace # 构建调试版 APK

      - name: Upload APK
        uses: actions/upload-artifact@v3 # 更新为 v3 版本
        with:
          name: my-build-apk
          path: app/build/outputs/apk/debug/*.apk # 根据项目的实际输出路径修改
